# Generated by Django 3.1 on 2020-08-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_follow_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdata',
            name='tweet',
            field=models.CharField(max_length=100),
        ),
    ]
